### ISSUE TITLE
Fetch image from <featureimg> tag

### ISSUE THREAD

**Issue by Kiran8899** [DigitalLeaves/SwiftFeedParser#10]
I am trying to fetch` featureimg` tag under which my image tag resides. I do not want the image from within the description tag. I made a feedImage variable in FeedItem and traversed the tag in FeedParser like this:

```
        else if self.currentPath == "/rss/channel/item/featureimg" {
            self.currentFeedItem?.feedImage = self.currentElementContent
            print("img : \(self.currentFeedItem?.feedImage)")
        }
```

The problem is that in the below method i get nil feedImage:

`func contentWasUpdated(_ extraContent: String? = nil) -> Void{`

I have put breakpoints and I realise that `contentWasUpdated ` is being called before its set through the code above. But for the feedDescription and all, its working fine.

**Comment by DigitalLeaves** [comment]
I don't get your point. Is this an error of the library? If this is something custom, please don't add that as an issue.
