### ISSUE TITLE
FeedParser doesn't parse more than 10 items

### ISSUE THREAD

**Issue by EdemAttiogbe** [DigitalLeaves/SwiftFeedParser#11]
Im my testing, it looks like the FeedParser doesn't parse more than 10 items, even when I test with a feed I know has more than 10 articles in it.  

'kReadyDefaultMaxFeedsToParse' is currently set to the default value of 20, but I've added dependency injection (and changed from a constant to a variable) to allow this value to be set to a different result.  Either way, even if I make this a much larger value, I still only get up to 10 parsed feed items.

**Comment by DigitalLeaves** [comment]
Hi Edem,
It should give you more than 10 items, if the feed contains them. Are you sure it has more than 10 items? Most feeds are paginated and use 10 by default. 

Anyway, I'm right now in the middle of the NSSpain conference, I will have a look by next week.

**Comment by EdemAttiogbe** [comment]
Thanks.  I looked into this a little bit more, and indeed, you were correct regarding pagination.  My source is Google's RSS new feeds, and they indeed paginate with 10 articles per page by default.  Good catch.

Edem

**Comment by DigitalLeaves** [comment]
Thanks Edem, glad to know it was that. Sorry for not getting back to you earlier on your first message, you got me at a conference and work peak.
Best regards!
