### ISSUE TITLE
Setting mainImage

### ISSUE THREAD

**Issue by EdemAttiogbe** [DigitalLeaves/SwiftFeedParser#12]
It looks like mainImage within FeedItem doesn't get set after a feed is successfully parsed.  It is always nil for me.  How is mainImage suppose to get set?  I don't think I follow how it is supposed to work.

I noticed that within FeedItem, the FeedItemDelegate doesn't get set anywhere to a conforming class:

`var delegate: FeedItemDelegate?`

Am I suppose to conform to FeedItemDelegate somewhere?

**Comment by DigitalLeaves** [comment]
It depends on many factors. Right now, it's not set unless you explicitly do so. The reasons for this are mainly the way in which different parsers process and access the images of the feeds, the presence of fake ad images, etc. The recommended way of doing that (the one I use) is extracting the image URLs via the getImageURLsFromContent method and then, if you successfully download one that's appropriate for you (width, height, type, etc), set it at the feed item.
